// <auto-generated />
using System;
using KgysProjectIdentity.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KgysProjectIdentity.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241021065507_PaymentDescription")]
    partial class PaymentDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KgysProjectIdentity.Core.Areas.Admin.ViewModel.UserAndValueListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAndValue");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.AccidentKgysModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidenKgysType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentComplementInsuranceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentComplementPolicyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentDamagePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccidentEbysNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentExpertiseCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentExpertiseEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentExpertiseEmailSend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentExpertiseTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentInsuranceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentKgysDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentKgysName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentPolicyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccidentRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccidentRegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentRegistrationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccidentReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlcoholTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountPaid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepairFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccidentKgys");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.AlertModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CalenderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("start")
                        .HasColumnType("datetime2");

                    b.Property<string>("textColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionCalender");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CctvEbysNumbersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DetailId")
                        .HasColumnType("int");

                    b.Property<string>("EbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CctvEbysNumbers");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CctvEk1Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoruData")
                        .HasColumnType("int");

                    b.Property<int>("BoruEnerji")
                        .HasColumnType("int");

                    b.Property<int>("Caat6Dis")
                        .HasColumnType("int");

                    b.Property<int>("Cat6Ic")
                        .HasColumnType("int");

                    b.Property<int>("Cat6Panel")
                        .HasColumnType("int");

                    b.Property<int>("DataPriz")
                        .HasColumnType("int");

                    b.Property<int>("DetailId")
                        .HasColumnType("int");

                    b.Property<int>("DisBullet")
                        .HasColumnType("int");

                    b.Property<int>("DomeTip1")
                        .HasColumnType("int");

                    b.Property<int>("DomeTip2")
                        .HasColumnType("int");

                    b.Property<int>("DuvarKabin")
                        .HasColumnType("int");

                    b.Property<int>("EnerjiKablo")
                        .HasColumnType("int");

                    b.Property<int>("EnerjiPano")
                        .HasColumnType("int");

                    b.Property<int>("EnerjiPriz")
                        .HasColumnType("int");

                    b.Property<int>("FoPanel")
                        .HasColumnType("int");

                    b.Property<int>("FoSingle")
                        .HasColumnType("int");

                    b.Property<int>("IcSwitch")
                        .HasColumnType("int");

                    b.Property<int>("KGK")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek10M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek3M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek4M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek5M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek6M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek7M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek8M")
                        .HasColumnType("int");

                    b.Property<int>("KameraDirek9M")
                        .HasColumnType("int");

                    b.Property<int>("KameraKontrol")
                        .HasColumnType("int");

                    b.Property<int>("KameraYazilim")
                        .HasColumnType("int");

                    b.Property<int>("Kanalet")
                        .HasColumnType("int");

                    b.Property<int>("KaziAsfalt")
                        .HasColumnType("int");

                    b.Property<int>("KaziToprak")
                        .HasColumnType("int");

                    b.Property<int>("LedTv")
                        .HasColumnType("int");

                    b.Property<int>("MetakKanal")
                        .HasColumnType("int");

                    b.Property<int>("Mic")
                        .HasColumnType("int");

                    b.Property<int>("Monitor")
                        .HasColumnType("int");

                    b.Property<int>("NvrTip1")
                        .HasColumnType("int");

                    b.Property<int>("NvrTip2")
                        .HasColumnType("int");

                    b.Property<int>("OtoSigorta")
                        .HasColumnType("int");

                    b.Property<int>("PcTip1")
                        .HasColumnType("int");

                    b.Property<int>("PcTip2")
                        .HasColumnType("int");

                    b.Property<int>("PtzKamera")
                        .HasColumnType("int");

                    b.Property<int>("RackKabin")
                        .HasColumnType("int");

                    b.Property<int>("SahaKabin")
                        .HasColumnType("int");

                    b.Property<int>("SahaSwitch")
                        .HasColumnType("int");

                    b.Property<int>("SistemPerformans")
                        .HasColumnType("int");

                    b.Property<int>("UyariLevha")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CctvEk1");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CctvModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CctvProjectDetail");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CctvProductsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DetailId")
                        .HasColumnType("int");

                    b.Property<string>("FloorOfProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorOfSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannedPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductPieces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CctvProducts");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CctvProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CctvProjects");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.CctvProjectPictureModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CctvDetailId")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CctvPictures");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.DistrictModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("districtName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DistrictModels");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.IpPhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CableIsTrue")
                        .HasColumnType("bit");

                    b.Property<string>("Campus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Central")
                        .HasColumnType("bit");

                    b.Property<string>("CentralBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhonePieces")
                        .HasColumnType("int");

                    b.Property<bool>("PoeSwitch")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedPersonel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IpPhoneProject");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.KgysPlannedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CameraCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfActivated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfPlanned")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DomeCameraCount")
                        .HasColumnType("int");

                    b.Property<string>("KgysName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KgysRequestId")
                        .HasColumnType("int");

                    b.Property<string>("LastStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectAssembly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCabinet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectConnection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCoordinate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectCoordinateX")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<decimal>("ProjectCoordinateY")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectEnergyCable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectEnergyConnect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectExcavation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectFiberOptic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectPole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectProtocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRecording")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectYear")
                        .HasColumnType("int");

                    b.Property<int?>("PtsCameraCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TelecomFoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KgysPlanned");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.KgysRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KgysName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectCoordinateX")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<decimal>("ProjectCoordinateY")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAnswerFromDisctrictEbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestArrangementNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestArraviedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestAskToDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAskToDistrictEbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCoordinate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestEvaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestEvaluationDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestFirstDiscovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestGoToDiscovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethodDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByWho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByWhoDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedTelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TelecomFoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KgysRequest");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.KgysRequestedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerFromDisctrictEbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArraviedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AskToDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AskToDistrictEbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluationDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinishedOrNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstDiscovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoToDiscovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastDiscovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByWho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByWhoDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KgysRequested");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.KuppaMultiplierModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Multiplier")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KuppaMultipliers");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogModel");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.MaterialsDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtmysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialBrandCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSpecification1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoTake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialsDetail");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.MaterialsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.MaterialsProductsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialsProductsModels");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.ModelForCctvProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductsModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModelForCctv");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.NanetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nanet");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.NeighbourModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("districtId")
                        .HasColumnType("int");

                    b.Property<string>("neighbourName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NeighbourModels");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.OfficialsJobsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OfficialsJobs");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.ParkAndRecreationsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ParkAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ParkCamerasActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParkCamerasIsActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkCamerasSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkCoordinate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkDistrictType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParkDomeCameraCount")
                        .HasColumnType("int");

                    b.Property<string>("ParkExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParkFixedCameraCount")
                        .HasColumnType("int");

                    b.Property<string>("ParkLiveMonitoring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkNeighboor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkNvrAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParkPoleCount")
                        .HasColumnType("int");

                    b.Property<string>("ParkSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkSupervisorTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParkTotalCameraCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParkAndRecreations");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.PaymentCodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentCode");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.PaymentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentEbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentPrice")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.PriorityForIpPhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PriorityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriorityForPhone");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.ProductsOfCctvProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductsOfCctv");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.ProjectEightyImagedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectEightyImagedModel");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.ProjectsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectsModels");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.RepetitiveRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerEbysNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestArraviedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByWho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByWhoDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedTelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepetitiveRequest");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.SecondaryRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutialFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcImaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedPersonel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SecondaryRequestModels");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.SecurityCodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecurityCode");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.TelecomFoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckEGM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EomStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpymStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KuppaDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KuppaDistance")
                        .HasColumnType("int");

                    b.Property<string>("KuppaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuppaPStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuppaPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MplsNmsStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MplsOperationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectCoordinateX")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<decimal>("ProjectCoordinateY")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<string>("ReportToEgm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SlaStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemosNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Vlan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.TelecomTeamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TelecomTeam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TelecomTeams");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.TenderOfAdmissionCommissionOfficialsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OfficialsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TenderOfAdmissionCommissionOfficials");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.TenderOfSpecificationOfficialsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OfficialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TenderOfSpecificationOfficials");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.TenderProjectsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionCommissionEbys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionCommissionEstablished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerEbysNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionerConfirmation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceEbysNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceOfWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestEbysNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendOfTender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationEbys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TenderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeOfWork")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfTender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoHasJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoRequested")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoResponse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TenderProjects");
                });

            modelBuilder.Entity("KgysProjectIdentity.Repository.Models.WaitingJobsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBYSanswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EbysNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinishOrNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalkToManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaitingJobs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("KgysProjectIdentity.Repository.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KgysProjectIdentity.Repository.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KgysProjectIdentity.Repository.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("KgysProjectIdentity.Repository.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KgysProjectIdentity.Repository.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KgysProjectIdentity.Repository.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
